<!DOCTYPE html>
<html>

<head>
    <title>Hi</title>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        td,
        th {
            border: 1px solid #000;
            /* text-align: left; */
            /* padding: 1px; */
            font-size: 14px;
        }

        /* body {
            background: rgb(204, 204, 204);
        } */

        /* page {
            background: white;
            display: block;
            margin: 0 auto; */
        /* margin-bottom: 0.5cm; */
        /* box-shadow: 0 0 0.5cm rgba(0, 0, 0, 0.5); */
        /* padding: 1cm 1cm 1cm 1cm;
        } */

        /* page[size="A4"] {
            width: 21cm;
            height: 29.7cm;
        }

        page[size="A4"][layout="landscape"] {
            width: 29.7cm;
            height: 21cm;
        }

        page[size="A3"] {
            width: 29.7cm;
            height: 42cm;
        }

        page[size="A3"][layout="landscape"] {
            width: 42cm;
            height: 29.7cm;
        }

        @media print {

            body,
            page {
                margin: 0;
                box-shadow: 0;
            }
        } */
    </style>
</head>

<body>
    <!-- <page size="A3"> -->
    <div class="row">
        <h5>DAFTAR : LAPORAN PENGELUARAN BAHAN MAKANAN KERING INSTALASI GIZI</h5>
        <h5>BULAN : DESEMBER 2018</h5>
    </div>
    <div class="row">
        <table border="1" width="100%">
            <tr style="text-align:center">
                <th rowspan="2">No</th>
                <th rowspan="2">Bahan</th>
                <th rowspan="2">Sat.</th>
                <th rowspan="2">Sisa Bln Lalu</th>
                <th rowspan="2">Penerimaan Bln Ini</th>
                <th colspan="31" style="text-align:center">Tanggal</th>
                <th rowspan="2">Jml</th>
                <th rowspan="2">Jml Pakai</th>
                <th rowspan="2">Sisa</th>
            </tr>
            <tr style="text-align:center; font-weight: bold;">
                <td>1</td>
                <td>2</td>
                <td>3</td>
                <td>4</td>
                <td>5</td>
                <td>6</td>
                <td>7</td>
                <td>8</td>
                <td>9</td>
                <td>10</td>
                <td>11</td>
                <td>12</td>
                <td>13</td>
                <td>14</td>
                <td>15</td>
                <td>16</td>
                <td>17</td>
                <td>18</td>
                <td>19</td>
                <td>20</td>
                <td>21</td>
                <td>22</td>
                <td>23</td>
                <td>24</td>
                <td>25</td>
                <td>26</td>
                <td>27</td>
                <td>28</td>
                <td>29</td>
                <td>30</td>
                <td>31</td>
            </tr>
            <tr>
                <td colspan="39" style="background: #e7eaf6; font-weight:bold; padding-left:10px;">A. Beras/Ketan/Mie/Jagung DLL</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Tepung Beras</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Tepung Terigu</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Tepung Tapioka</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Tepung Maizena</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Tepung Roti</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Baking Powder</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Tepung Agar Agar</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Mie Instan</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Kerupuk Udang Kecil</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Bks</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <!-- <tr>
                <td colspan="39" style="background: #e7eaf6; font-weight:bold; padding-left:10px;">B. Gula/Teh/Kopi/Sirup</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr>
                <td colspan="39" style="background: #e7eaf6; font-weight:bold; padding-left:10px;">C. Minuman/Susu DLL</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr>
                <td colspan="39" style="background: #e7eaf6; font-weight:bold; padding-left:10px;">D. Plastik Roll/Plastik/Kantong Plastik/Sedotan Plastik DLL</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr>
                <td colspan="39" style="background: #e7eaf6; font-weight:bold; padding-left:10px;">E. Minyak Goreng/Mentega DLL</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr>
            <tr style="text-align:center">
                <td>1</td>
                <td>Beras C4</td>
                <td>Kg</td>
                <td>320</td>
                <td>2500</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>11</td>
                <td>22</td>
                <td>33</td>
                <td>44</td>
                <td>55</td>
                <td>66</td>
                <td>77</td>
                <td>88</td>
                <td>99</td>
                <td>100</td>
                <td>100</td>
                <td>11</td>
                <td>11</td>
                <td>11</td>
            </tr> -->
        </table>
    </div>
    <!-- </page> -->
</body>

</html>
